apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
#Author: Bikram Kumar Pattanaik
metadata:
  name: app
  namespace: default
spec:
  minReplicas: 4
  maxReplicas: 15
  targetCPUUtilizationPercentage: 15
  scaleTargetRef:
    apiVersion:  apps/v1
    kind: Deployment
    name: app-deployment