apiVersion: batch/v1
kind: Job
metadata:
  name: loadtest1
spec:
  template:
    spec:
      containers:
      - name: siege
        image: schoolofdevops/loadtest:v1
        command: ["siege", "--concurrent=5", "--benchmark", "--time=10m", "http://13.89.224.36:8085"]
      restartPolicy: Never
  completions: 2
  parallelism: 1